### ISSUE TITLE
refactor: please consider anything that doesn't need to internal packages

### ISSUE THREAD

**Issue by ccoVeille** [go-sprout/sprout#104]
### Please exprime yourself

Go internal packages allows to isolate code and easy refactoring without having to wonder if someone using directly and exported thing.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi @ccoVeille, what do you mean?
Do you have something specific in mind or any examples?

I’m asking because internal is already used for all "no-template" exported functions (like helpers used across multiple registries), and helpers are not exported outside the registry package.

**Comment by ccoVeille** [comment]
For me pesticide and deprecated should at least be in internal.

And I wonder if registry couldn't

**Comment by 42atomys** [comment]
- `pesticide` can be used by the registry developer outside the sprout project.  
- `deprecated` is scheduled to be removed in `v1.1`. In my opinion, we can leave it here for now.  

Registry and Group must not be internal because, if they are, nobody will be able to import and use them.

**Comment by ccoVeille** [comment]
OK then. For now, it's OK I assume
