### ISSUE TITLE
bug: missing TxtFuncMap

### ISSUE THREAD

**Issue by andig** [go-sprout/sprout#29]
### Describe the bug

Boticed when upgrading from 0.2. While not strictly necessary, this is a nice helper and required to maintain compatibility.

### To Reproduce

see below

### Expected behavior

Function available

### Code Snippet

```Shell
template.New("yaml").Funcs(sprout.TxtFuncMap()).Parse(...)
```

### Version of software

v0.3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andig** [comment]
Note: if this is accepted as issue I'd consider it a regression in 0.3

**Comment by 42atomys** [comment]
What a chaotic migration 🤦 Apologies for missing this functions, missing functions are :
- HermeticTxtFuncMap
- HermeticHtmlFuncMap
- TxtFuncMap
- HtmlFuncMap
- GenericFuncMap

This is a regression and I takes the decision to rollback the v0.3.0 to include back the functions !

**Comment by 42atomys** [comment]
@andig you can re-pull `v0.3.0` version the issue has addressed directly on the version to prevent regression 

Thanks again for your reactivity 🙏

**Comment by andig** [comment]
> you can re-pull v0.3.0 version the issue has addressed directly on the version to prevent regression

Btw, that is a particularly bad idea. One the version has been cached- either goproxy or in e.g. Github actions cache- it will not be pulled again. The proper way to fix this is a new release and- if very bad- retracting the old release. Not a big thing, but this shouldn't become a habit. In this case, it has made 0.3.0 unusable for me.
