### ISSUE TITLE
misc: document differences with sprig

### ISSUE THREAD

**Issue by sathieu** [go-sprout/sprout#39]
### Please exprime yourself

sprout changed behavior of some functions. It would be great to have a place with the list of behavior changes.

At least:

- https://github.com/go-sprout/sprout/pull/35
- https://github.com/go-sprout/sprout/pull/34
- removed functions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hello @sathieu,

Thank you for bringing this to our attention. I agree with you that this point requires a clear migration process, particularly when considering the differences between implementations aimed at resolving bugs versus adding unit tests. Our goal is also to remove all panics from the templating system.

Best regards,
Atom
