### ISSUE TITLE
Approach to template errors

### ISSUE THREAD

**Issue by infogulch** [go-sprout/sprout#5]
Hi! I'm happy to see a project run with what sprig started; I think there's a lot of space for improvement. 😄 (I'm considering switching right away just to dodge the mergo fiasco. Don't drink and drive, and don't change your import path in a release, kids. 😆)

I see that you briefly mention improving template error handling. I'm using sprig in [my own project](https://github.com/infogulch/xtemplate) that revolves around go templates, and I've also found that error handling is a thorny problem. I don't think the solution is to just swallow all errors. Sometimes an error protects you you from a bad program state, but other times it would be nice to be able to handle an error state within the template explicitly.

The strategy I came up with is adding the [`try` func](https://github.com/infogulch/xtemplate/blob/aefa33ec863774482161be9c4d77e24b7f007bb5/funcs.go#L227-L285). It's similar to Go's `call` builtin, but instead of sending the error to the template executor it wraps both the error and any value in a `type result struct {Value any;Error error}` that the template author can use to handle the error as they wish. Combined with a method on the dot context that returns any named func as a value, this gives authors the ability to call the func normally, stopping execution if it errors as usual, or they can handle an error themselves by calling it via `try`.

I'm curious what you think about this strategy, and what ideas you were considering.

🏹🎯

**Comment by 42atomys** [comment]
Hi @infogulch,

Thank you for interest for this early fork and raising this important topic and contributing your ideas to improve error handling in template system. I've thought about your proposal and would like to expand on the idea of enhancing error handling with a few additional strategies that could work well with the `try` function concept you introduced:

## **Flexible Error Handling Outside of Templates**:
   I could introduce mechanisms to handle errors in multiple ways, depending on the severity and context:
   - **Panic**: force the process to halt.
   - **Default Value**: providing a fallback default value could allow templates to continue running smoothly.
   - **Template Error Handling (Default)**: Maintain a default error handling mechanism that integrates seamlessly into the existing workflow, enabling errors to be managed directly within the go template logic.

  Example of **Default Value** strategy: 
  ```go
    // Never panic, always return default value to continue execution
    fnHandler := sprout.NewFunctionHandler(
      sprout.WithErrStrategy(sprout.ErrorStrategyReturnDefaultValue),
    )

    tmpl, err := template.New("foo").Funcs(sprout.FuncMap(sprout.WithFunctionHandler(fnHandler))).ParseGlob("*.sprout.tmpl")
  ```

## **Introduction of `try` / `tryCatch` Functions**:
   These functions would give template authors the ability to explicitly opt to handle errors and continue execution. The `try` function could catch the error and optionally return a predefined default value, ensuring that the template can proceed without interruption (Like the **Default Value** mechanism explain above).

  ```go 
  {{ define "codeblock" }}Block to execute with potential errors {{ end }}
  {{ tryTemplate "codeblock" . }}

  {{ define "codeblock" }}Block to execute with error {{ .. Syhtnax-%Error }} {{ end }}
  {{ define "errorblock" }}Block to execute when error occurs {{ end }}
  {{ tryCatchTemplate "codeblock" "errorblock" . }}
  ```

## **Adding a `tryErr` Function** (like you proposed :purple_heart:):
  This function would return both the result and the error, enabling more granular error handling within the templates. This would allow template authors to handle the error states directly in the template logic

   ```go
   {{ $output := tryErr .MyFunc }}
   {{ with $output }}
       Result: {{ .Value }}, Error: {{ .Error }}
   {{ end }}
   ```

These enhancements aim to provide robust, flexible, and intuitive error handling capabilities to our template system. I believe integrating these features would significantly improve our error management strategy, making our templates more resilient and easier to maintain.

I'm looking forward to your thoughts on these proposals! 🚀 

> [!NOTE]
> Function names are not contractual and can change

Best regards,

**Comment by infogulch** [comment]
These are some interesting ideas, though I'm not sold on all of them yet. 😋

Here are some of the thoughts I had while reading your post and the linked PR:

* Panicking is completely inappropriate here, templates should never panic when they can just return an error when calling `err := tmpl.Execute(w, dot)`. If the user wants to panic on error they can do that themselves by inspecting the returned err. (Unless by panic you mean something different than Go `panic()`.)
* This style of config seems like a lot of boilerplate
* Default values instead of errors are ok I guess but I don't see the point when you have something like try. I'd rather a new func with a different name that returns a default value in case of an error instead of dynamically changing the error behavior of funcs depending on some setup configuration.
* Doing something stateful with functions like sending errors out on a channel seems like a terrible idea considering that one template can be executed in multiple goroutines at the same time and funcs don't have access to the local dot context unless it's passed in explicitly by the template itself, at which point you might as well use `try`.

### Fallback templates

I've considered adding fallback templates to my system; aka a template that runs instead when the original template execution fails. (I think this is similar to your tryCatch idea.) For me since I'm writing a web server this might be implemented as special template names based on the http error code; e.g. if template execution exits with (say) error code 500 then the template `{{define "500"}}...{{end}}` is executed instead.

This is fine, but it would have to be implemented by inspecting the result of calling `err := tmpl.Execute(w, dot)`, and then looking up and calling a different template manually. I.e. this has to be implemented in the Go code that calls Execute, it couldn't be implemented inside the template execution context. Another wrinkle with this strategy is that you'd have to explicitly buffer the result, since you should expect the `w` passed to `Execute` has data written to it basically immediately, and if it errors out halfway through rendering then it probably won't make sense to keep writing to the same w, but to render and write a different response entirely. Buffering can be fine in certain situations (I use it in xtemplate) but it would represent a big change in the way users have to execute templates to get this feature.

### `return` func

This also has to be implemented by in the surrounding Go code, but you can create a special sentinel error type that can be used to exit template rendering early without it being considered an "error". In my case it looks like this:

```go
// return causes the template to exit early with a success status. Added to the FuncMap with the name `return`.
func FuncReturn() (string, error) {
	return "", ReturnError{}
}

// ReturnError is a sentinel value that indicates a successful/normal exit but
// causes template execution to stop immediately.
type ReturnError struct{}

func (ReturnError) Error() string { return "returned" }

var _ error = ReturnError{}
```

But, again, to implement this I had to add code to specifically handle this case after the call to `tmpl.Execute`:

```go
func (dotXProvider) Cleanup(_ any, err error) error {
	if errors.As(err, &ReturnError{}) {
		return nil
	}
	return err
}
```

This code is a bit out of context, but in short Cleanup is called after template execution ends with the value returned by `tmpl.Execute` and it has a chance to alter the error; in this case if its the special `ReturnError` type then the 'error' is swallowed.

The semantics this provides is that the template author can add `{{return}}` to their template in any control flow branch to stop execution and prevent rest of the template from being rendered.

**Comment by 42atomys** [comment]
Hi @infogulch,

Thank you for your detailed feedback and for engaging so constructively on these error handling strategies. Your insights have certainly helped refine the approach, and I’ve taken some time to reconsider the best paths forward based on our discussion. Here’s how I plan to adjust the error handling mechanisms in the project:

## Error Handling Strategies
**Panic Handler**: I agree that using panic should not be included as a strategy and it was mainly included initially for testing purposes. This will not be part of the stable release. Thanks for reinforcing the importance of avoiding such extremes in production code.

**Default Value Handler**: This has proven very useful in scenarios where operations need to continue safely despite errors, ensuring that template rendering can proceed without interruption. We will retain this as an optional strategy.

**Template Error (Default)**: Respecting Go's conventions, this strategy will be the default. It follows the traditional text/template error handling by stopping execution and returning errors, ensuring that error handling is explicit and transparent.

**Error Channel**: Your point are correct, I think about large applications needing a centralized error handling mechanism is well taken. Instead of being a separate strategy, we will integrate it as an optional feature that can complement the default error handling. This will allow errors to be collected and handled externally, possibly in batches, which is beneficial for monitoring and logging in complex systems.


## New and Refined Approaches
We will simplify the options to primarily focus on either **DefaultValue** or **TemplateError** as the only strategies for now, with the ability to toggle between them based on the application’s needs.

**Error Channels** will be implemented as an adjunct to these main strategies, allowing errors to be streamed to a channel for external handling or logging, thus providing more flexibility without complicating the core error handling logic.

**Error Wrapping**: This is something I'm considering introducing to allow for more granular error handling. It would help in providing more context around errors, making them easier to debug and handle. **I will focus on that point**.

**Try/TryCatch and TryErr Functions**: Inspired by your try function suggestion and my usage across projects, these will be designed to provide template authors with tools to handle errors directly within templates, enhancing control over error management.

## Moving Forward
These changes aim to balance robust error handling with flexibility and adherence to Go's best practices, ensuring that developers can tailor the behavior to their specific needs without overwhelming the core functionality.

I appreciate your role in driving these improvements, and I’m eager to hear any further thoughts you might have as we refine these strategies!

Best regards,

**Comment by infogulch** [comment]
I still don't see the point of the default value mode and would prefer a way to wrap existing erroring funcs into funcs that return a default value with a different name instead of changing the meaning of func errors at load time. But I haven't tried it and you say you've found it to be useful, so I'll let you cook. 👨‍🍳

The error wrapping idea is intriguing, template errors are generally pretty sparse and getting more context could be very useful. But I don't know how this could be implemented technically, especially within the function.

I still doubt the utility of an error channel. First, the only information available is the name of the function, the parameters, and the function's error response, but none of the context; if you call that function a dozen times in your templates there's no telling where that error occurred. Though maybe the error wrapping idea above will ameliorate this issue. Second, I'm concerned that this would make the user vulnerable to a DoS attack where an attacker can cause many goroutines to block on writing to the same channel from different cores. The consequence of contention would not be a problem if errors are rare, but an attacker could trigger the error path intentionally so it would not be rare. Though maybe this is an acceptable risk in some deployments.

Thank you for taking a dynamic stance towards my feedback while maintaining a firm vision for what you want the library to become.

**Comment by infogulch** [comment]
Wait, you basically just want to log errors. Why not log to a `*log.Logger` or `*slog.Logger` instead of to a channel.

**Comment by 42atomys** [comment]
Hi @infogulch,

Thanks for your continued engagement and valuable input! Your insights are shaping this project in exciting ways. Here’s the approach we’re planning based on our discussions:

## Integrated Logging with `slog.Logger`
We already have the capability to configure logging through `slog.Logger` with [`WithLogger()`](https://github.com/42atomys/sprout/blob/main/sprout.go#L63) as you pointed out. 🎉 

## Error Wrapping Module
I’m focusing on developing a comprehensive error wrapping module that aims to capture detailed context from errors occurring in nested function calls within templates. The goal is to make debugging as straightforward as possible by preserving the chain of errors and contexts. For instance, in a template chain like {{ "[42]" | parseJson | toInt | add "1" }}, we want to catch and clearly articulate errors from each function, ideally showing how one error leads to another, thus providing a clear error pathway.

## ErrChan as a Consideration
While the `ErrChan` currently serves as a means to facilitate centralized error management, it's crucial to assess its necessity based on the effectiveness of our upcoming error wrapping module. If the error wrapping achieves our goals of clarity and comprehensiveness, the reliance on ErrChan might be significantly reduced. It could potentially be decommissioned, allowing users to implement it as they see fit within their own environments.

## Next Steps
I'm diving deep into the **error wrapping module** and will keep you updated. If you’re interested, I’d love to ping you with updates or a demo in the coming days once we have something tangible to review.

Thank you once again for helping make this tool more robust and developer-friendly. 
Your feedback is not only appreciated—it’s integral to the project!

Best regards,

**Comment by 42atomys** [comment]
Hi @infogulch, 

according to the new direction of the project, I decide to restart the discussion from the beginning : With a [RFC 📓 ](https://github.com/orgs/go-sprout/discussions/32)

I takes in consideration what we talk about here (no errChan anymore 👀) in the proposals, feel free to give feedback on the RFC directly : https://github.com/orgs/go-sprout/discussions/32

I close this issue to continue on discussion instead, thanks for your early feedback 💜 🌱
