### ISSUE TITLE
bug: Not all documentation examples work

### ISSUE THREAD

**Issue by lewisdenny** [go-sprout/sprout#78]
### Describe the bug

Hi,

While I was evaluating the use of sprout I noticed some of the documented function examples don't work.

I will focus on cat but the same issue is with all functions that include commas. It wasn't until I read the Go test cases that I understood how to use the functions in a template. I didn't see any other reports of this issue so I assume I'm either misusing or misunderstanding the documentation but I would expect the "Template Example" to work in a template.

Thank you!

### To Reproduce

I have a commented go dev link showing the issue: https://go.dev/play/p/LdHAcF0TY33

I will also paste the code here:
```go
package main

import (
	"html/template"
	"log"
	"os"

	"github.com/go-sprout/sprout"
	"github.com/go-sprout/sprout/registry/std"
)

func main() {

	handler := sprout.New()
	handler.AddRegistry(std.NewRegistry())
	funcs := handler.Build()

	// From https://docs.atom.codes/sprout/introduction/getting-started
	tpl1, err := template.New("example").Funcs(funcs).Parse(`{{ hello }}`)
	if err != nil {
		log.Fatal(err)
	}
	tpl1.Execute(os.Stdout, nil)

	// Working version of cat
	tpl2, err := template.New("example").Funcs(funcs).Parse(`{{ cat "Hello" nil 123 true }}`)
	if err != nil {
		log.Fatal(err)
	}
	tpl2.Execute(os.Stdout, nil)

	// From https://docs.atom.codes/sprout/registries/std#cat
	tpl3, err := template.New("example").Funcs(funcs).Parse(`{{ "Hello", nil, 123, true | cat }}`)
	if err != nil {
		log.Fatal(err)
	}
	tpl3.Execute(os.Stdout, nil)

}
```

### Code Snippet

```Shell

```

### Version of software

main

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi, thanks for reporting that, in documentation `,` are present and comma don't work on template, good catch 👏 

I will do a deep pass on the documentation today !

**Comment by lewisdenny** [comment]
Ah, thank goodness, I thought I was somehow doing something wildly wrong lol. 

Let me know if you don't have time for this. I can submit a patch this week.

**Comment by 42atomys** [comment]
Thank you for the proposal. If you don’t see a PR related to this issue by the end of the week, feel free to contribute—you are very welcome! 🚀
