### ISSUE TITLE
proposal: toYaml should allow to set a level of indentation

### ISSUE THREAD

**Issue by mrueg** [go-sprout/sprout#79]
### You have a proposal, explain it!

Right now toYaml will indent with 4 spaces per level by default. 
If the rest of the document is formatted with 2 spaces per level it will not format it correctly.

### Describe the solution you'd like

It would be great to either have an optional parameter for toYaml or have an explicit function for toYamlWithCustomIndent that allows setting the indentation.

Before Marshalling, you can set the Indent with:
https://pkg.go.dev/gopkg.in/yaml.v3?utm_source=godoc#Encoder.SetIndent 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi, thanks for your proposition. That makes sense to me to have a customization for indentation like `ident`. The best solution would be to provide a function `ToIndentYaml` to enable this kind of usage:
```gotmpl
{{ $d := dict "name" "John Doe" "age" 30 }}
{{ $d | toIndentYaml 2 }}
```

Additionally, check if this is possible with `ToPrettyJson`.
