### ISSUE TITLE
misc: fix methods cases

### ISSUE THREAD

**Issue by ccoVeille** [go-sprout/sprout#84]
### Please exprime yourself

Right now, it's

- toJson
- toYaml
- fromJson
- ...

But these are acronyms

It should be
- toJSON
- toYAML
- fromJSON

The code is OK I think. My problem is the identifier of methods in the template engine

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ccoVeille** [comment]
I thought about it by reading

- https://github.com/go-sprout/sprout/pull/82

**Comment by ccoVeille** [comment]
> 👋 Thank you for bringing this up. 
> 
> Initially, I hesitated to adopt Go's idiomatic naming conventions for acronyms, as most Go template engines don't follow this practice, and I was concerned about confusing users. Since I was the sole advocate for this approach and there was no prior feedback, I aligned with existing engines.

But, is there a need to have case sensitive identifier in the template?

I mean:
- tojson
- toJson
- toJSON
-tOJsON

Is it important?

> However, with renewed interest and support for adhering to these conventions, I'm now inclined to update the method names to align with Go's idiomatic practices. This change is also consistent with our documentation, which [recommends following the style guide for idiomatic naming conventions, including initialisms](https://docs.atom.codes/sprout/introduction/templating-conventions#:~:text=Follow%20the%20style%20guide%20for%20Idiomatic%20Naming%20Convention%20(e.g.%2C%20Initialisms)).

👍

> My only ⚠ point is to provide an alias from the old `toJson` to the new `toJSON` and add a [deprecation notice](https://docs.atom.codes/sprout/features/function-notices#deprecated) to ensure backward compatibility with Sprig in v1.0.0.

Of course.

**Comment by 42atomys** [comment]
> But, is there a need to have case sensitive identifier in the template?

Unfortunately, the standard Go template engine is case-sensitive, which indeed can be frustrating at times. It limits flexibility and requires developers to adhere to strict naming conventions. While this behavior aligns with Go's philosophy of simplicity and explicitness, it often feels unnecessarily rigid in the context of template engines.

Introducing case-insensitivity in Sprout would significantly increase complexity and potentially hurt performance. 
To keep the engine lightweight and efficient, we’ve opted to stick with the default behavior.

_Create a new template engine better than the std lib can be the next project 👀_

**Comment by ccoVeille** [comment]
OK, so adding and supports toJson as an alias of toJSON (and the same for Yaml+ indent variations) would be enough

**Comment by 42atomys** [comment]
Yes that will be enough and in a far future the alias can be dropped.

**Comment by ccoVeille** [comment]
maybe toYamlIdent could be renamed without alias as you added it recently

**Comment by 42atomys** [comment]
> maybe toYamlIdent could be renamed without alias as you added it recently

As not deployed yet, yes do it without alias ✅
